<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>palletrone_cmd</name>
  <version>0.0.1</version>
  <description>Palletrone keyboard and Lissajous command publisher</description>

  <maintainer email="ryung9514@naver.com">ryung</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>ament_index_cpp</depend>
  <depend>yaml-cpp</depend>
  <depend>eigen</depend>
  <depend>palletrone_interfaces</depend>
  <depend>std_msgs</depend>

  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>plant</exec_depend>
  <exec_depend>palletrone_controller</exec_depend>
  <exec_depend>palletrone_visualization</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
